### ISSUE TITLE
Need a guided tour (walk through) for the Editor

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-lang/composer#131]
<a href="https://github.com/dilinisg"><img src="https://avatars.githubusercontent.com/u/1845370?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dilinisg](https://github.com/dilinisg)**
_Monday Jan 23, 2017 at 12:37 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/958_

----

Need a guided tour (walk through) for the Editor. Otherwise it will not be very clear for a new or non-technical person to start with it.

**Comment by hevayo** [comment]
The motivation is to make the editor intuitive so that the user does not require a guided tour. Further more we will be creating some videos to help users adopt the composer.
