### ISSUE TITLE
Errorneous statement gets reverted on enter

### ISSUE THREAD

**Issue by maheeka** [ballerina-lang/composer#2076]
Click on an assignment and start typing
<img width="150" alt="image" src="https://user-images.githubusercontent.com/1029806/27438754-de54a40a-5783-11e7-9389-ea104621d939.png">

During typing, following is an erroneous statement. 
<img width="168" alt="image" src="https://user-images.githubusercontent.com/1029806/27438770-e7730536-5783-11e7-923e-daa36639be1d.png">

If user looses focus at this point (by mistake), everything is reverted back to the old state, resulting the user to start typing from beginning.

**Comment by hevayo** [comment]
We need display an error when the content is not valid.

**Comment by maheeka** [comment]
Current behaviour is as follows.

When user types syntactically incorrect source, the source is reverted and an error message is displayed.
<img width="226" alt="image" src="https://user-images.githubusercontent.com/1029806/32718113-f5c38142-c853-11e7-9739-a6e1e14c3616.png">
<img width="162" alt="image" src="https://user-images.githubusercontent.com/1029806/32718119-fac914a4-c853-11e7-810f-2fa6821337f8.png">

We should disable falling back on the editing mode when hit enter with syntactically incorrect code.  
@hevayo  WDYT?
