### ISSUE TITLE
Cannot export the diagram as a PNG

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#2659]
Release - 0.91
Firefox

Cannot export the diagram as a PNG

**Comment by NipunaMarcus** [comment]
This looks like firefox browser related disability. 
https://bugzilla.mozilla.org/show_bug.cgi?id=788226
I'm currently researching on ways to fix this issue.

**Comment by dilinisg** [comment]
Can still observe in 0.95 release
