### ISSUE TITLE
Annotations are not available in the exported SVG

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#2660]
Release 0.91

Following is the actual diagram (in left) and downloaded diagram as a SVG. 

![svg1](https://user-images.githubusercontent.com/1845370/28918193-01fedc1a-7866-11e7-959f-8e1dc5176e2a.png)

**Issues**
1. Annotations are not shown. 
2. Alignment issues in the parameters of the function

**Comment by NipunaMarcus** [comment]
Diagram export is only considering the SVG element when exporting diagram as png and svg. Annotation details are drawn using HTML which will be excluded in this method as it is not SVG. To include annotations when exporting diagram either we have to implement them using SVG or convert them to SVG during exporting diagram.   This will be discuss further and try to find a solution.

**Comment by dilinisg** [comment]
Can still observe in 0.95 release

![32](https://user-images.githubusercontent.com/1845370/32407190-462e6e3a-c1ab-11e7-99a9-d364d2ae0256.png)
