### ISSUE TITLE
404 for documentation support for some connectors

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#2951]
Release 0.93

No doc support for the following connectors

- Twitter
- LinkedIn
- oauth2
- soap etc

![4042](https://user-images.githubusercontent.com/1845370/29807541-08264352-8cb2-11e7-969a-c483ae2e4854.png)

**Comment by NipunaMarcus** [comment]
Documents for these connectors are not yet available. Added issue for Docerina to track the this issue. please refer: https://github.com/ballerinalang/docerina/issues/111
