### ISSUE TITLE
Debugger does not work properly for worker.

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#2981]
**Issue:**
When try to debug workers first time break point doesn't hit. But sometimes break point get hit but at that time all the debug points above and outside the worker won't get hit. This is happening intermittently. So hard to tell what break point will get hit.

**Comment by NipunaMarcus** [comment]
This need to be checked in ballerina core level  - https://github.com/ballerinalang/ballerina/issues/3274
