### ISSUE TITLE
Issues in the exported images of compact and action views

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#2997]
Release 0.93

![expimgact](https://user-images.githubusercontent.com/1845370/30013021-8d46398a-9161-11e7-8010-806450d89fd2.png)

![imgcompact](https://user-images.githubusercontent.com/1845370/30013013-82585c10-9161-11e7-8cf4-e4d490f7d093.png)

**Comment by NipunaMarcus** [comment]
This issue is occurs only on Firefox and it is happening because of css property `dominant-baseline` doesn't work properly in firefox.
