### ISSUE TITLE
High latency in the composer

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#3193]
Release 0.93

The following latencies are identified in the composer in the cloud.

- Around 20 seconds to Create an application
- Around 1 minute to open the composer and load the source view
- Around 1 minute to switch to the design view. Sometimes not loading the design view at all (Continuously loading for more than 10 mins)
- Minimum 30 seconds to deploy and run a service. Sometimes cannot deploy a service at all. Stuck with the message "Running helloService.bal service"

**Comment by manjulaRathnayaka** [comment]
FYI. 

> Around 20 seconds to Create an application

This is to create the Ballerina service and the composer for editing that Ballerina service. Earlier we created the composer when the user clicks on 'Open Ballerina Composer' but now the composer also created as part of the Ballerina service creation process.

**Comment by hevayo** [comment]
This is no longer relevant.
