### ISSUE TITLE
Xml backquote statement get reset when added through design view

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-lang/composer#3402]
Version: 0.93
Browser: Chrome Version 61.0.3163.100

Steps
1. Add variable declaration
`xml a`
2. Add assignment statement and type the following
```a = xml `<<?target data?>` ```
3. Press enter

The statement get reset. Issues as this will generate a user experience switch from design view to source view, but this is not a point where it should happen

**Comment by NatashaWso2** [comment]
Related issue : #3402  Switches to source view when xml backquote statement is used

**Comment by hevayo** [comment]
We no longer give an option to edit statement from design view, hence closing the issue.
