### ISSUE TITLE
Different text sizes in directory structure

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-lang/composer#3687]
Browser: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

Please see the attached image. The directory structure contain different text sizes. Let's have standard text size and styling to have an uniform effect.

![com_0 94_textsize](https://user-images.githubusercontent.com/15624590/31508278-2a9432da-af9b-11e7-88a2-0832429f222f.png)

**Comment by maheeka** [comment]
The idea behind this difference is that the topmost folder is the Program directory and the rest that appear are directories supporting the package hierarchy. Hence the difference in emphasis

**Comment by manuranga** [comment]
@dakshika @srsharon  Please verify this is ok, and please close if it is.

**Comment by srsharon** [comment]
The sizes in the directory have been brought to one fixed size. 

This has been fixed in the 0.96 release please find attached screen dump 
![image](https://user-images.githubusercontent.com/10986966/34663097-f4afb570-f47a-11e7-9877-06bea9d26531.png)
