### ISSUE TITLE
Some of the list menus have layout issues

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#3884]
Windows-firefox
![31](https://user-images.githubusercontent.com/1845370/31648070-6857a246-b329-11e7-9771-e25b119a6817.PNG)

**Comment by maheeka** [comment]
Also as seen on above, the border of the file explorer crosses the menu in other OS and browsers. 
<img width="196" alt="image" src="https://user-images.githubusercontent.com/1029806/32850696-c2822c38-ca2a-11e7-9177-b0c9858a493a.png">
