### ISSUE TITLE
Try-it cannot identify all the services that are up and running in a package

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#3908]
1. Have multiple services in a package
2. Run one file from the composer. All the services should be up and running
3. Go to try-it and verify the services drop down

**Issue**
Only the service that the user ran is visible in the drop donw

**Comment by dilinisg** [comment]
Observed in 0.95 release as well

**Comment by maheeka** [comment]
Hi Dilini, are you referring to having a Ballerina program where services are in different bal files?

If it is multiple services in one bal file, this is working at the moment.
<img width="642" alt="image" src="https://user-images.githubusercontent.com/1029806/32849980-ade7ba1a-ca28-11e7-8618-360cccea9a33.png">

We will revisit the package scenario with new package improvements that are under development
