### ISSUE TITLE
Wrong error mesage when a native function is added

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#4005]
This error is not meaningful
![11](https://user-images.githubusercontent.com/1845370/31770134-182c914c-b4f4-11e7-84a7-234b6776a3b0.png)

**Comment by dilinisg** [comment]
This is applicable for var type
![28](https://user-images.githubusercontent.com/1845370/31779840-b3ad37a8-b511-11e7-82d8-df2088b1c6ca.png)

**Comment by maheeka** [comment]
This is because if invalid scope check in trasform. Closing this issue to track with https://github.com/ballerinalang/composer/issues/3898
