### ISSUE TITLE
[Annotation] When a longer sentence is given for doc params a slight disort happen

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-lang/composer#4214]
Browser: Chrome Version 62.0.3202.62 (Official Build) (64-bit)

Please see the attached image. The sentence is in a newline and the annotation box is placed on top of it

![com_0 94_clientconnector_3](https://user-images.githubusercontent.com/15624590/32090521-70375af6-bb0d-11e7-97a3-022ac5c4a95c.png)

**Comment by hevayo** [comment]
This annotation UI was removed form composer.
