### ISSUE TITLE
Improve program directory related experience 

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-lang/composer#4306]
- When a user tries to open a packaged file within a program dir, ask whether user wants to open the program dir too and open upon confirmation.
- When a user adds a package to a file for the first time,
           - If it's a new file which not yet persisted, upon save, in save dialog, show a check box with message that we need to create the sub folder for package structure.
           - if it's file which is already saved, display an alert with same message and provide a btn to create folder structure and move file there
- when a user changes the package of a opened file, ask and move file to correct directory
- provide a wizard to create a file within program dir and a package

**Comment by NipunaMarcus** [comment]
Also kavith we need Rename and Sync file structure from the disk functionality to be added to the composer.
Related issues: 
#4253

**Comment by kaviththiranga** [comment]
@NipunaMarcus, WDY mean by sync file structure?

**Comment by NipunaMarcus** [comment]
@kaviththiranga  Mean when refresh the project explorer we should be able to see added files from outside of the composer or renamed directory.

**Comment by kaviththiranga** [comment]
![asknopen-program-dir](https://user-images.githubusercontent.com/1505855/33262429-391f7a84-d38c-11e7-8f83-30685c6c88dc.gif)

Completed below item
When a user tries to open a packaged file within a program dir, ask whether user wants to open the program dir too and open upon confirmation.
