### ISSUE TITLE
Remove ImageUtils for loading icons

### ISSUE THREAD

**Issue by maheeka** [ballerina-lang/composer#4346]
Need to use font icons everywhere and remove image utils. The panels and other places except for tool palette use image utils. We should use fonts everywhere.

**Comment by hevayo** [comment]
We use image utils to embed icons svg inside the diagram svg, IMO replacing that with the font will be not strait forward, the best bet would be to create a tag similar to <i ...></i> for svg.

**Comment by dakshika** [comment]
AFAIK we can't use "i" on SVG. But we can map font character code on SVG text. We can add font family to text and use svg content

**Comment by hevayo** [comment]
https://stackoverflow.com/questions/14984007/how-do-i-include-a-font-awesome-icon-in-my-svg

**Comment by hevayo** [comment]
Fixed in 0.964.0
