### ISSUE TITLE
Cannot access the option list in the action view where "Hidden Code" text is

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#4495]
Cannot access the option list (debug/delete etc) in the action view where "Hidden Code" text is.
![44](https://user-images.githubusercontent.com/1845370/32422651-8456558e-c2c7-11e7-9a52-6b2fcdce74ba.png)

**Comment by kaviththiranga** [comment]
@dilinisg In action view, hidden code meant to be like that

**Comment by kaviththiranga** [comment]
user has to switch to default view to work with hidden nodes. This is the expected behaviour

**Comment by nadeeshaan** [comment]
Closing the issue based on the previous comment

**Comment by dilinisg** [comment]
Hi all,
I think you have misunderstood what I meant. What I wanted to say is the option list of the first statement (var nameString, _ = ...) is covered from the label "Hidden Text". Hence, we cannot debug that statement. Reopening the issue
