### ISSUE TITLE
OutOfMemoryError in composer

### ISSUE THREAD

**Issue by dilinisg** [ballerina-lang/composer#4562]
Could not access the composer from the browser. The following error was thrown from the back-end.
`./composer: line 206:  4685 Killed                  $JAVACMD -Xms256m -Xmx1024m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="$BAL_COMPOSER_HOME/logs/heap-dump-tool.hprof" -Djava.util.logging.config.file="$BAL_COMPOSER_HOME/bre/conf/composer-logging.properties" $JAVA_OPTS -classpath "$COMPOSER_CLASSPATH" -Djava.io.tmpdir="$BAL_COMPOSER_HOME/tmp" -Djava.command="$JAVACMD" -Dballerina.home="$BAL_COMPOSER_HOME" -Dbal.composer.home="$BAL_COMPOSER_HOME" -Djava.security.egd=file:/dev/./urandom -Dfile.encoding=UTF8 -Dcomposer.port=9091 -DenableCloud=false -Dworkspace.port=8289 -Dtransports.netty.conf=./resources/composer/services/netty-transports.yml -Dmsf4j.conf=./resources/composer/services/deployment.yaml org.ballerinalang.composer.service.workspace.app.WorkspaceServiceRunner $@
`

No heap dump was available in $BAL_COMPOSER_HOME/logs/heap-dump-tool.hprof location

**Comment by NipunaMarcus** [comment]
Is this happened on the 0.95.1? if this happened again please put the code that you were working on so we can try to reproduce.
