### ISSUE TITLE
[Improvement] Provide git support in composer

### ISSUE THREAD

**Issue by erandidesilva** [ballerina-lang/composer#4639]
When switching between branch1 and branch2, currently the composer does not load the files accordingly. Since switching may cause some changes in files, it's better to reflect this in composer. Hence it would be good to provide git support by reloading files automatically when a change is detected.

**Comment by NipunaMarcus** [comment]
There is a file sync menu item in the file explorer menu. User can use that to sync the project with the file system's latest updates. We will work on the feature for reloading project structure automatically.
