### ISSUE TITLE
Debug menu run option is not disables when reopened

### ISSUE THREAD

**Issue by yasassri** [ballerina-lang/composer#4662]
**Description:**
If you click on run again, this leads to starting multiple processes which makes composer unusable.

![screenshot from 2017-11-18 17-37-00](https://user-images.githubusercontent.com/7681361/32980133-3608ecc4-cc87-11e7-84b1-5ab468fc03f7.png)

**Affected Product Version:**
0.95.1

**OS, DB, other environment details and versions:**    
Firefox

**Comment by pahans** [comment]
@yasassri can you provide steps to reproduce this issue?
