### ISSUE TITLE
Inconsistency in code formatiing when adding connectors

### ISSUE THREAD

**Issue by yasassri** [ballerina-lang/composer#4665]
**Description:**
![screenshot from 2017-11-18 17-56-46](https://user-images.githubusercontent.com/7681361/32980304-ea30529e-cc89-11e7-801e-38cdf5b1decb.png)

**Affected Product Version:**
0.95.1

**OS, DB, other environment details and versions:**    
Firefox

**Comment by NipunaMarcus** [comment]
This is happening only when you drag and drop a connector action without drag and drop an endpoint first. If we drag and drop an endpoint first endpoint code formatting are okay.
