### ISSUE TITLE
Undo dosn't jump to last edited location.

### ISSUE THREAD

**Issue by manuranga** [ballerina-lang/composer#4690]
**Description:**
Usability issue, undo dosn't jump to last edited location.

**Affected Product Version:**
0.95.0

**Steps to reproduce:**
1. Edit text
2. Click different place
3. Press undo

**Comment by kaviththiranga** [comment]
Currently our undo manager is overriding the behaviour of source-editors one and have a unified logic for undo/redo for both design changes and source changes. It just takes the new source replaces the old source with undo/redo. Hence, there is no way to handle previous cursor position unless we save the same inside the undo/redo stack.

However, if we follow a hybrid approach for handling undo/redo - that is, using the built-in undo manager of source-editor when in source view and refactor the composer undo manager logic accordingly, we can solve this easily and properly.
