### ISSUE TITLE
[Transformer] Differentiate between parameters and variables

### ISSUE THREAD

**Issue by maheeka** [ballerina-lang/composer#4762]
**Description:**
Currently, there is no differentiation in the view between parameters and variables. We need a visual way of differentiating between them. 
Also, ability to switch a variable or a parameter (e.g. make a variable a parameter) could be a valid feature too.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/1029806/33411224-5c856a54-d5aa-11e7-883b-63956b62581c.png">

**Affected Product Version:** 0.95.1

**OS, DB, other environment details and versions:**    N/A

**Comment by keizer619** [comment]
Could include a icon like this {p} for parameters

**Comment by maheeka** [comment]
Ah yes. we can't have {v} for parameters.

I think we need a better separation. i.e. color, horizontal line or a grouping of some sort.
