### ISSUE TITLE
Preserving parentheses in source gen

### ISSUE THREAD

**Issue by manuranga** [ballerina-lang/composer#4776]
**Description:**
Parentheses disappears after UI operations.

**Related .bal file source**
```
function x (int a, int b, int c) {
    var x = ( a + b ) * c;
}
```
**Related Issues:**
Depends on ballerinalang/ballerina#4219

**Comment by maheeka** [comment]
Also reported in https://github.com/ballerinalang/composer/issues/3085 and https://github.com/ballerinalang/composer/issues/709
