### ISSUE TITLE
remove jquery dependency or bump version to latest

### ISSUE THREAD

**Issue by kaviththiranga** [ballerina-lang/composer#4983]
AFAIR we currently use jquery in some trivial use cases only. A lot of dependencies of jquery were removed when we revamped the composer as a react app. Find the possibility of getting rid of jquery completely or at least bump the version to a latest one to avoid security issues.

**Comment by keizer619** [comment]
We have used jQeury in Transformer, for DOM manipulations related to jsPlumb [1]. We could replace those with pure JS.

[1] https://github.com/ballerinalang/composer/blob/master/modules/web/src/plugins/ballerina/diagram/views/default/components/transformer/transformer-render.js
