### ISSUE TITLE
Worker line plus position breaks when adding a new worker

### ISSUE THREAD

**Issue by keizer619** [ballerina-lang/composer#4986]
This only happens if you add a worker inside Resource. Seems like worker scope add a spacing

![screen shot 2018-01-23 at 4 32 21 pm](https://user-images.githubusercontent.com/2918812/35272179-5c060ef0-005a-11e8-86d8-9029eeb070a3.png)

**Comment by srsharon** [comment]
![image](https://user-images.githubusercontent.com/10986966/35314594-3cb4d232-00ed-11e8-8147-5f3a133fda3a.png)

There is also an additional plus that comes on the left corner of the service and function container.
