### ISSUE TITLE
Composer not render properly on chrome  Version 63.0.3239.108 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by dakshika** [ballerina-lang/composer#5026]
**Description:**
Composer looks wired on welcome page and hello world sample

**Affected Product Version:**
latest master commit 42e8544bd6014f81c1ff76ac68483894273987f8

**OS, DB, other environment details and versions:**    
Linux Ubuntu 16.04
Version 63.0.3239.108 (Official Build) (64-bit)

![180207balcomposer](https://user-images.githubusercontent.com/6497326/35901411-754d9f74-0bfc-11e8-9d4b-79497c015755.png)
![180207balcomposer2](https://user-images.githubusercontent.com/6497326/35901412-757d706e-0bfc-11e8-897b-4d43925d6462.png)

**Comment by hevayo** [comment]
This is fixed in 0.961.0
