### ISSUE TITLE
We should provide multiline edit box (wrapped text, not to get new lines) when editing large text

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-lang/composer#707]
<img width="1189" alt="screen shot 2017-02-15 at 11 09 21 pm" src="https://cloud.githubusercontent.com/assets/2410076/22987174/ea5352c4-f3d3-11e6-9d07-398c4da2f75b.png">

For example, look at excel/ google spread sheet on how they allow editing large text.

**Comment by hevayo** [comment]
The design has changed and we are no longer let users to edit expression in the diagram 0.961.0+
