### ISSUE TITLE
Opened Ballerina files on Ballerina editor (graphical view) cannot be reordered.

### ISSUE THREAD

**Issue by Sewmi** [ballerina-lang/composer#835]
Ballerina files that are opened in Ballerina editor  (graphical view) cannot be reordered as user preferred.

<img width="1438" alt="ballerina_composer_reordering" src="https://cloud.githubusercontent.com/assets/7960586/23090690/29ebacf4-f5ca-11e6-82fe-897d980362ef.png">

**Comment by dakshika** [comment]
this will be get fixed after the golden layout implementation

**Comment by dakshika** [comment]
We have dropped golden layout. hence issue still valid
